name: test

on:
  pull_request:
    branches:
      - master
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - setup.py
  push:
    branches:
      - master
    paths:
      - src/**
      - tests/**
      - pyproject.toml
      - setup.py
    tags:
      - v*

jobs:
  test:
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version:
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
        include:
        - os: ubuntu-22.04
          python-version: '3.7'
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}
        cache: pip
    - name: Update pip
      run: pip install -U pip
    - name: Install package, and lint and test requirements
      run: pip install
        --requirement ./tests/requirements.txt
        pytest pytest-cov .
    - name: Test with pytest
      run: |
        pytest -vvra \
          --cov proxpi \
          --cov-report xml \
          --cov-report term \
          --cov-config pyproject.toml
    - name: Upload coverage
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  lint:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: 3.x
        cache: pip
    - name: Update pip
      run: pip install -U pip
    - name: Install lint requirements
      run: pip install black isort
    - name: Lint with black
      run: black --check src/
    - name: Sort imports with isort
      run: isort --check src/
